name: build
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cygwin base packages with chocolatey
        run: |
          choco install --no-progress cygwin

      - name: Set ENV
        run: |
          echo 'PATH=C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin' >> $GITHUB_ENV

      - name: Test check wget
        run: |
          echo $PATH
          ls C:\tools\cygwin\bin
          ls C:\tools\cygwin\package

      - name: Init /usr/local
        run: |
          sh ./scripts/init-local.sh

      - name: Download sources
        run: |
          sh ./scripts/download.sh

      - name: Build binutils
        run: |
          sh ./scripts/build-binutils-2.15.sh

      - name: Build gcc
        run: |
          sh ./scripts/build-gcc.sh

      - name: Build newlib
        run: |
          sh ./scripts/build-newlib.sh
